spring:
 application.name: NativeQuery
 
 application: 
  name: Employee-Management-System
 
 datasource:
  url: jdbc:postgresql://localhost:5432/studentdb
  username: postgres
  password: password
 
 jpa:
  hibernate:
   ddl-auto: update
   
server:
 port: 8081
 
 servlet:
  context-path: /api/v1
